SELECT
    AVA.RA,
    PP.NOME AS ALUNO,
    MPL.CODTURMA,
    STD.CODTURMA AS CODTURMA_2,
    ATD.IDTURMADISC,
    STD.CODDISC,
    SD.NOME AS DISCIPLINA,
    ETP.ETAPA AS ETAPA_PAI,
    ETP.DESCRICAO AS DESC_ETAPA_PAI,
	ETP.LABEL as SEMESTRE,
    AV.NOME AS AVALIACAO,
    AV.TIPO AS TIPO_AVALIACAO,
    AV.PESO,
    AV.NOTAMAXIMA ,
    ATD.DATA AS DATA_APL_PROVA,
    AVA.NOTA AS NOTA_ALUNO,
    CONCAT('https://diario.escolamobile.com.br/php/imagem_carometro.php?ra=',AVA.RA) AS FOTO,
    GETDATE() as 'ULTIMA_ATUALIZACAO',
    case
		when lic.PERCFEITAS is null then '-'
		else lic.PERCFEITAS  
	end as 'LICAO_DE_CASA',
	CASE	
		WHEN STD.CODDISC LIKE '%.I' THEN 'Interdisciplinar'
		WHEN STD.CODDISC LIKE '%.E' THEN 'Eletiva'
		WHEN (STD.CODDISC = 'ING' OR STD.CODDISC = 'ESP') THEN 'Turma Mista'
	ELSE 'Regular'
		END AS TIPO_DISCIPLINA,
        ET.DESCRICAO AS PERIODO,
        AV.PUBLICAR,
		SPL.CODPERLET as 'ANO_LETIVO',
		CASE
			WHEN AV.ULTIMOPERIODO IS NULL THEN 0
			ELSE AV.ULTIMOPERIODO
		END AS 'ULTIMOPERIODO'
    -- falt.FALTAS,s
    -- falt.FALTASSTR
   FROM
    DiarioMB.dbo.ETAPAS ET
    INNER JOIN DiarioMB.dbo.ETAPAS ETP ON ETP.ETAPA = ET.ETAPAPAI
    INNER JOIN DiarioMB.dbo.AVALIACOES AV ON AV.ETAPA = ET.ETAPA
    INNER JOIN DiarioMB.dbo.AVALIACOESTURMASDISC ATD ON ATD.AVALIACAO = AV.AVALIACAO
    INNER JOIN DiarioMB.dbo.AVALIACOESALUNOS AVA ON AVA.AVALIACAO = AV.AVALIACAO
    INNER JOIN CorporeRM.dbo.SMATRICULA MAT ON MAT.CODCOLIGADA = ATD.CODCOLIGADA AND MAT.IDTURMADISC = ATD.IDTURMADISC AND MAT.RA = AVA.RA
    INNER JOIN CorporeRM.dbo.SMATRICPL MPL ON MPL.CODCOLIGADA = MAT.CODCOLIGADA AND MPL.IDPERLET = MAT.IDPERLET AND MPL.IDHABILITACAOFILIAL = MAT.IDHABILITACAOFILIAL AND MPL.RA = MAT.RA
    INNER JOIN CorporeRM.dbo.SALUNO SA ON SA.CODCOLIGADA = MPL.CODCOLIGADA AND SA.RA = MPL.RA
    INNER JOIN CorporeRM.dbo.PPESSOA PP ON PP.CODIGO = SA.CODPESSOA
    INNER JOIN CorporeRM.dbo.SPLETIVO SPL ON SPL.CODCOLIGADA = MPL.CODCOLIGADA AND SPL.IDPERLET = MPL.IDPERLET
    INNER JOIN CorporeRM.dbo.SSTATUS SST ON SST.CODCOLIGADA = MPL.CODCOLIGADA AND SST.CODSTATUS = MPL.CODSTATUS
    INNER JOIN CorporeRM.dbo.STURMADISC STD ON STD.CODCOLIGADA = MAT.CODCOLIGADA AND STD.IDTURMADISC = MAT.IDTURMADISC
    INNER JOIN CorporeRM.dbo.SDISCIPLINA SD ON SD.CODCOLIGADA = STD.CODCOLIGADA AND SD.CODDISC = STD.CODDISC
    left join DiarioMB.dbo.REL_LICOESALUNOS as lic on lic.RA = ava.RA and lic.CODTURMA = mpl.CODTURMA and lic.CODDISC = std.CODDISC
    and lic.CODREDUZIDO = etp.CODREDUZIDO
    -- left join DiarioMB.dbo.VW_FALTASALUNOS as falt on falt.RA = ava.RA and falt.CODTURMA = mpl.CODTURMA and falt.CODDISC = std.CODDISC
   WHERE
   1=1
    -- AV.PUBLICAR = 1
    AND SPL.CODPERLET >= 2023
    and MPL.CODTURMA not like 'C%'
    and SST.PLATIVO = 'S'
	and ETP.DESCRICAO like '%Integral%'
    -- AND ETP.ETAPA = '547' /* 1º Semestre - Médio - Período Parcial */
    -- and ava.RA = 140365
    -- and std.CODDISC = 'QUI'
                ;
