WITH CTE_ORDEM_COMPRA AS
(
    SELECT
        TM.CODCOLIGADA,
        TM.IDMOV,
        TM.DATAEMISSAO,
        TMC.REQUISICAO_NRO,
        TMC.REQUISICAO_SOLICITAN,
        TMC.REQUISICAO_STATUS,
        TIT.IDPRD,
        TIT.QUANTIDADE,
        TIT.CODUND,
        TP.NOMEFANTASIA AS PRODUTO,
        TCC.CODCOTACAO
    FROM
        TMOV TM
        INNER JOIN 
            TMOVCOMPL TMC ON TMC.CODCOLIGADA = TM.CODCOLIGADA AND TMC.IDMOV = TM.IDMOV
        INNER JOIN 
            TITMMOV TIT ON TIT.CODCOLIGADA = TM.CODCOLIGADA AND TIT.IDMOV = TM.IDMOV
        INNER JOIN 
            TPRD TP ON TP.CODCOLIGADA = TIT.CODCOLIGADA AND TP.IDPRD = TIT.IDPRD
        LEFT JOIN 
            TCCOTACAOITMMOV TCT ON TCT.CODCOLIGADA = TIT.CODCOLIGADA AND TCT.IDMOV = TIT.IDMOV AND TCT.NSEQITMMOV = TIT.NSEQITMMOV
        LEFT JOIN 
            TCCOTACAO TCC ON TCC.CODCOLIGADA = TCT.CODCOLIGADA AND TCC.CODCOTACAO = TCT.CODCOTACAO
    WHERE
        TM.CODCOLIGADA = 1
        AND    TM.CODTMV = '1.1.20'
),
CTE_SOLICITACAO_COMPRA AS
(
    SELECT
        TM.CODCOLIGADA,
        TM.IDMOV,
        TM.DATAEMISSAO,
        TMC.REQUISICAO_NRO,
        TMC.REQUISICAO_SOLICITAN,
        TMC.REQUISICAO_STATUS,
        TIT.IDPRD,
        TIT.QUANTIDADE,
        TIT.CODUND,
        TP.NOMEFANTASIA AS PRODUTO,
        TCC.CODCOTACAO,
        CASE
            WHEN HAB.CODSTATUS = 'A' THEN 'Em andamento'
            WHEN HAB.CODSTATUS = 'R' THEN 'Concluído a responder'
            WHEN HAB.CODSTATUS = 'O' THEN 'Concluído respondido'
            WHEN HAB.CODSTATUS = 'F' THEN 'Concluído confirmado'
            WHEN HAB.CODSTATUS = 'U' THEN 'Concluído automático (pelo sistema)'
            WHEN HAB.CODSTATUS = 'V' THEN 'Avaliado'
            WHEN HAB.CODSTATUS = 'G' THEN 'Agendado a responder'
            WHEN HAB.CODSTATUS = 'E' THEN 'Agendado respondido'
            WHEN HAB.CODSTATUS = 'T' THEN 'Aguardando terceiros'
            WHEN HAB.CODSTATUS = 'C' THEN 'Cancelado'
            WHEN HAB.CODSTATUS = 'D' THEN 'Despertado'
            END STATUS_APROVACAO
    FROM
        TMOV TM
        INNER JOIN 
            TMOVCOMPL TMC ON TMC.CODCOLIGADA = TM.CODCOLIGADA AND TMC.IDMOV = TM.IDMOV
        INNER JOIN 
            TITMMOV TIT ON TIT.CODCOLIGADA = TM.CODCOLIGADA AND TIT.IDMOV = TM.IDMOV
        INNER JOIN 
            TPRD TP ON TP.CODCOLIGADA = TIT.CODCOLIGADA AND TP.IDPRD = TIT.IDPRD
        LEFT JOIN 
            TCCOTACAOITMMOV TCT ON TCT.CODCOLIGADA = TIT.CODCOLIGADA AND TCT.IDMOV = TIT.IDMOV AND TCT.NSEQITMMOV = TIT.NSEQITMMOV
        LEFT JOIN 
            TCCOTACAO TCC ON TCC.CODCOLIGADA = TCT.CODCOLIGADA AND TCC.CODCOTACAO = TCT.CODCOTACAO
        LEFT JOIN 
            TCCOTACAOATEND TCE ON TCE.CODCOLIGADA = TCC.CODCOLIGADA AND TCE.CODCOTACAO = TCC.CODCOTACAO
        LEFT JOIN 
            HATENDIMENTOBASE HAB ON HAB.CODCOLIGADA = TCE.CODCOLIGADA AND HAB.CODATENDIMENTO = TCE.CODATENDIMENTO
    WHERE
        TM.CODCOLIGADA = 1
        AND    TM.CODTMV = '1.1.10'
),
CTE_REQUISICAO_PORTAL AS
(
    SELECT 
        RCE.*,
        RCES.descricao AS status_desc
    FROM
        intranet.dbo.requisicao_compra_externa RCE
        INNER JOIN 
            intranet.dbo.requisicao_compra_externa_status RCES ON RCES.id = RCE.status
    WHERE
        1=1
        AND RCE.data_insercao >= '2024-09-23'

),
CTE_CENTRO_CUSTO AS
(
	SELECT
		CODCOLIGADA,
		CODCCUSTO,
		NOME AS CENTRO_CUSTO
	FROM
		PCCUSTO
	WHERE
		CODCOLIGADA = 1
		AND ATIVO = 'T'
)

SELECT
    distinct
    RP.id AS ID_REQUISICAO,
    RP.titulo AS TITULO,
    RP.status AS STATUS,
    RP.status_desc AS STATUS_DESC,
    RP.data_insercao AS DATA_INSERCAO_REQUISICAO,
	RP.data_previsao,
	RP.data_aprovacao AS PRIMEIRA_APROVACAO,
    SC.CODCOLIGADA,    
    SC.IDMOV,    
    SC.DATAEMISSAO,    
    SC.REQUISICAO_NRO,    
    SC.REQUISICAO_SOLICITAN,    
    SC.CODCOTACAO,    
    SC.STATUS_APROVACAO,
    OC.IDMOV AS ORDEM_COMPRA_IDMOV,
	CC.CENTRO_CUSTO
FROM
    CTE_REQUISICAO_PORTAL RP
    LEFT JOIN 
        CTE_SOLICITACAO_COMPRA SC ON SC.REQUISICAO_NRO = RP.id
    LEFT JOIN 
        CTE_ORDEM_COMPRA OC ON OC.CODCOTACAO = SC.CODCOTACAO AND OC.CODCOLIGADA = SC.CODCOLIGADA
	LEFT JOIN
		CTE_CENTRO_CUSTO CC ON CC.CODCCUSTO = RP.id_requisicoes_grupos COLLATE SQL_Latin1_General_CP1_CI_AI
ORDER BY
    1;