SELECT
	TB.ANOLETIVO,
	CASE
		WHEN TB.TURNO <> 'INTEGRAL' THEN CONCAT(TB.SERIE_FORMAT,' - ',TB.TURNO)
		ELSE TB.SERIE_FORMAT
		END AS serie,
	TB.MANIFESTACOES as 'manifestacoes'
FROM (
	SELECT
		TB.CODPERLET AS ANOLETIVO,
		UPPER(TB.PERIODO_PRIMEIRA_OPCAO) AS TURNO,
		G.NOME AS SERIE,
		CASE
			WHEN G.NOME LIKE '%EDUCAÇÃO INFANTIL%' THEN RIGHT(G.NOME,10)
			WHEN G.NOME LIKE '%ENSINO FUNDAMENTAL%' THEN LEFT(G.NOME,6)
			WHEN G.NOME LIKE '%ENSINO MÉDIO%' THEN LEFT(G.NOME,6)
			WHEN G.NOME LIKE '%INTEGRAL%' THEN G.NOME
			END AS SERIE_FORMAT,
		COUNT(*) AS MANIFESTACOES
	FROM
		(
		SELECT
			P.CODPERLET,
			I.CODCURSO_PRETENDIDA,
			I.CODHABILITACAO_PRETENDIDA,
			M.PERIODO_PRIMEIRA_OPCAO,
			CASE
				WHEN M.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA,'.1')
				ELSE CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA)
				END AS CODGRADE
		FROM
			INSCRICAO I
			INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
			INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
		WHERE
			P.ID_PROCESSO = 13
		) TB
		INNER JOIN GRADE G ON G.CODGRADE = TB.CODGRADE
	GROUP BY
		TB.CODPERLET,
		TB.PERIODO_PRIMEIRA_OPCAO,
		TB.CODCURSO_PRETENDIDA,
		G.NOME
	) TB;