SELECT
    SPL.CODPERLET as 'ANO_LETIVO',
    MPL.RA as 'ALUNO_RA',
    CASE
        WHEN MPL.CODCOLIGADA = 2 THEN 'Médio'
        WHEN MPL.CODCOLIGADA = 1 AND ST.TIPO = 'I' THEN 'Integral'
        WHEN MPL.CODCOLIGADA = 1 AND ST.TIPO IN ('M','V') THEN 'Parcial' 
    END AS PERIODO
FROM
    SMATRICPL MPL
    INNER JOIN SPLETIVO SPL ON SPL.CODCOLIGADA = MPL.CODCOLIGADA AND SPL.IDPERLET = MPL.IDPERLET
    INNER JOIN SSTATUS SST ON SST.CODCOLIGADA = MPL.CODCOLIGADA AND SST.CODSTATUS = MPL.CODSTATUS
    INNER JOIN SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = MPL.CODCOLIGADA AND SHF.IDHABILITACAOFILIAL = MPL.IDHABILITACAOFILIAL
    INNER JOIN STURNO ST ON ST.CODCOLIGADA = SHF.CODCOLIGADA AND ST.CODTURNO = SHF.CODTURNO
WHERE
    MPL.CODCOLIGADA IN (1,2)
    AND SPL.CODPERLET >= '2022' /* ANO LETIVO */
     AND SST.PLATIVO = 'S';