SELECT
      AVA.RA as ra,
      GPA.PROVA_ALUNO as instrumentStudent,
      GPA. TIPO_PROVA instrumentType,
      AV.NOME as name,
      TD.CODTURMA as codturma,
      TD.CODDISC as coddisc,
      AV.NOTAMAXIMA as maxGrade,
      SL.DESCRICAO as room,
      SC.FILEIRA as row,
      SC.CARTEIRA as writingTable,
      ISNULL(AV.QUESTOES,120) as questions,
      ET.DESCRICAO AS periodo,
      ET.CODPERLET,
      G.DATA, 
      G.HORARIO,
	  PP.NOME
    FROM
      [DIARIO].dbo.GP_GRUPOS G
      INNER JOIN
        [DIARIO].dbo.GP_GRUPOS_SALAS GS ON GS.ID_GRUPO = G.ID_GRUPO
      INNER JOIN
        [DIARIO].dbo.GP_SALAS SL ON SL.ID_SALA = GS.ID_SALA
      INNER JOIN
        [DIARIO].dbo.GP_SALAS_CARTEIRAS_UTILIZADAS SC ON SC.ID_SALA = SL.ID_SALA AND SC.ID_GRUPO = G.ID_GRUPO
      INNER JOIN
        [DIARIO].dbo.GP_GRUPOS_PROVAS_ALUNOS GPA ON GPA.ID_CARTEIRA_UTILIZADA = SC.ID_CARTEIRA_UTILIZADA
      INNER JOIN
        [DIARIOMB].DBO.AVALIACOESALUNOS AVA ON AVA.AVALIACAOALUNO = GPA.PROVA_ALUNO
      INNER JOIN
        [DIARIOMB].DBO.AVALIACOES AV ON AV.AVALIACAO = AVA.AVALIACAO
      INNER JOIN
        [DIARIOMB].DBO.ETAPAS ET ON ET.ETAPA = AV.ETAPA
      INNER JOIN
        [DIARIOMB].DBO.AVALIACOESTURMASDISC AVT ON AVT.AVALIACAO = AV.AVALIACAO
      INNER JOIN
        [CORPORERM].DBO.STURMADISC TD ON TD.IDTURMADISC = AVT.IDTURMADISC AND TD.CODCOLIGADA = AVT.CODCOLIGADA
      INNER JOIN
        [CORPORERM].DBO.SMATRICULA MAT ON MAT.RA = AVA.RA AND MAT.IDTURMADISC = TD.IDTURMADISC
      INNER JOIN
        [CORPORERM].DBO.SSTATUS SST ON SST.CODSTATUS = MAT.CODSTATUS AND SST.CODCOLIGADA = MAT.CODCOLIGADA
      INNER JOIN
        [CORPORERM].DBO.SPLETIVO PL ON PL.IDPERLET = MAT.IDPERLET AND PL.CODCOLIGADA = MAT.CODCOLIGADA AND PL.CODPERLET = ET.CODPERLET
		inner join CorporeRM.dbo.SALUNO as SA on SA.RA = AVA.RA
		INNER JOIN CorporeRM.dbo.PPESSOA PP ON PP.CODIGO = SA.CODPESSOA

    WHERE
        SST.PLATIVO = 'S'
    ORDER BY
      SL.ID_SALA,
      SC.FILEIRA,
      SC.CARTEIRA