SELECT
    al.OFICINA AS AULA,
    al.DATA AS DATA,
    st.CODDISC,
    sd.NOME AS DISCIPLINA,
    pp.NOME,
    ala.OFICINAALUNO,
    ala.OFICINA,
    ala.RA,
    CASE
        WHEN ala.PRESENCA = 3 THEN 'Não Convocado'
        WHEN ala.PRESENCA = 4 THEN 'Convocado'
        WHEN ala.PRESENCA = 5 THEN 'Participou'
        WHEN ala.PRESENCA = 6 THEN 'Fez Atividade'
        WHEN ala.PRESENCA = 7 THEN 'Faltou'
        ELSE CONVERT(VARCHAR, ala.PRESENCA)
    END AS STATUS,
    ala.PONTUALIDADE,
    ala.MATERIAL,
        CASE
        WHEN shf.CODGRADE LIKE '030_' THEN 'MEDIO'
        WHEN shf.CODGRADE LIKE '0_0_.[1B]' THEN 'INTEGRAL'
        ELSE 'PARCIAL'
    END as 'Ciclo',
    st.CODTURMA,
	et.etapa,
    et.DESCRICAO
FROM
    [DiarioMB].dbo.ETAPAS et
INNER JOIN
    [DiarioMB].dbo.ETAPASTURMASDISC ett ON ett.ETAPA = et.ETAPA
INNER JOIN
    [DiarioMB].dbo.OFICINAS al ON al.DATA BETWEEN et.DATAINI AND et.DATAFIM AND al.IDTURMADISC = ett.IDTURMADISC
INNER JOIN
    [DiarioMB].dbo.OFICINASALUNOS ala ON al.OFICINA = ala.OFICINA
INNER JOIN
    CorporeRM.dbo.sturmadisc st ON ett.IDTURMADISC = st.IDTURMADISC AND et.CODCOLIGADA = st.CODCOLIGADA
INNER JOIN
    CorporeRM.dbo.SALUNO sa ON ala.RA = sa.RA AND et.CODCOLIGADA = sa.CODCOLIGADA
INNER JOIN
    CorporeRM.dbo.PPESSOA pp ON sa.CODPESSOA = pp.CODIGO
INNER JOIN
    CorporeRM.dbo.SDISCIPLINA sd ON st.CODCOLIGADA = sd.CODCOLIGADA AND st.CODDISC = sd.CODDISC
INNER JOIN     
    CorporeRM.dbo.SMATRICPL mpl on mpl.RA = ala.RA
INNER JOIN 
    CorporeRM.dbo.SHABILITACAOFILIAL shf ON shf.IDHABILITACAOFILIAL = mpl.IDHABILITACAOFILIAL AND shf.CODCOLIGADA = mpl.CODCOLIGADA
INNER JOIN 
    CorporeRM.dbo.SPLETIVO pl ON pl.IDPERLET = mpl.IDPERLET AND pl.CODCOLIGADA = mpl.CODCOLIGADA and pl.CODPERLET = et.CODPERLET
INNER JOIN
    CorporeRM.dbo.SSTATUS ST2 ON ST2.CODSTATUS = MPL.CODSTATUS AND ST2.CODCOLIGADA = MPL.CODCOLIGADA
WHERE
    et.CODPERLET = '2024'
    AND ST2.PLATIVO = 'S'
    and mpl.CODCOLIGADA <> 7
    -- AND ala.RA = 170134
    -- AND st.CODDISC = 'ESP'
ORDER BY
    pp.nome