SELECT
    E.DESCRICAO,
    ET.IDTURMADISC,
    ST.CODDISC,
    SD.NOME AS DISCIPLINA,
    ST.CODTURMA,
    ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) AS CODGRADE,
    FA.IDTURMADISC AS 'id_FECHADO',
    FA.DATAHORAREC AS 'data_fechado',
    CASE 
		when ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) like '%.[1B]' then 'Integral'
		WHEN ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) LIKE '%.1' THEN 'Integral'
		WHEN ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) LIKE '%.1' THEN 'Integral'
        WHEN ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) LIKE '03%' THEN 'Médio'
        WHEN ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) LIKE '02%' THEN 'Fundamental 2'
        WHEN ISNULL(SHF.CODGRADE,STC.CODGRADEINTCANVAS) LIKE '01%' THEN 'Fundamental 1'
        ELSE 'Médio'
    END AS CICLO
FROM
    ETAPAS E
    INNER JOIN ETAPASTURMASDISC ET ON E.ETAPA = ET.ETAPA
    INNER JOIN CorporeRM.dbo.STURMADISC ST ON ET.IDTURMADISC = ST.IDTURMADISC AND E.CODCOLIGADA = ST.CODCOLIGADA
    INNER JOIN CorporeRM.dbo.STURMA STU ON STU.CODCOLIGADA = ST.CODCOLIGADA AND STU.CODFILIAL = ST.CODFILIAL AND STU.CODTURMA = ST.CODTURMA AND STU.IDPERLET = ST.IDPERLET
    LEFT JOIN CorporeRM.dbo.SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = STU.CODCOLIGADA AND SHF.IDHABILITACAOFILIAL = STU.IDHABILITACAOFILIAL
    LEFT JOIN CorporeRM.dbo.STURMADISCCOMPL STC ON STC.CODCOLIGADA = ST.CODCOLIGADA AND STC.IDTURMADISC = ST.IDTURMADISC
    INNER JOIN CorporeRM.dbo.SDISCIPLINA SD ON SD.CODCOLIGADA = ST.CODCOLIGADA AND SD.CODDISC = ST.CODDISC
    LEFT JOIN FECHAMENTOSATAS FA ON ET.IDTURMADISC = FA.IDTURMADISC AND FA.ETAPA = E.ETAPA
WHERE
    E.CODPERLET = 2024;