WITH FUNIL AS
	(
	/* INSCRIÇÕES */
	SELECT
		P.CODPERLET,
		UPPER(C.NOME) AS CANDIDATO,
		I.CODCURSO_PRETENDIDA AS CODCURSO,
		I.CODHABILITACAO_PRETENDIDA AS CODHABILITACAO,
		UPPER(I.TURNO_PRETENDIDO) AS TURNO,
		'1 - INSCRIÇÃO' AS ETAPA,
		I.CRIADO_EM AS [DATA]
	FROM
		INSCRICAO I
		INNER JOIN CANDIDATO C ON C.ID_CANDIDATO = I.ID_CANDIDATO
		INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
	WHERE
		I.ID_PROCESSO IN (13,14)
	UNION ALL
	/* REUNIÕES */
	SELECT
		P.CODPERLET,
		UPPER(C.NOME) AS CANDIDATO,
		I.CODCURSO_PRETENDIDA AS CODCURSO,
		I.CODHABILITACAO_PRETENDIDA AS CODHABILITACAO,
        UPPER(I.TURNO_PRETENDIDO) AS TURNO,
		'2 - REUNIÃO' AS ETAPA,
		NULL AS [DATA]
	FROM
		INSCRICAO I
		INNER JOIN CANDIDATO C ON C.ID_CANDIDATO = I.ID_CANDIDATO
		INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
	WHERE
		I.ID_PROCESSO IN (13,14)
		AND I.ID_STATUS NOT IN (1,12,13)
	UNION ALL
	/* MANIFESTAÇÕES */
	SELECT
		P.CODPERLET,
		UPPER(C.NOME) AS CANDIDATO,
		I.CODCURSO_PRETENDIDA AS CODCURSO,
		I.CODHABILITACAO_PRETENDIDA AS CODHABILITACAO,
		CASE
			WHEN UPPER(M.PERIODO_PRIMEIRA_OPCAO) = 'MANHA' THEN 'MANHÃ'
			WHEN UPPER(M.PERIODO_PRIMEIRA_OPCAO) = 'UNDEFINED' THEN 'MANHÃ'
			ELSE UPPER(M.PERIODO_PRIMEIRA_OPCAO)
			END AS TURNO,
		'3 - MANIFESTAÇÃO' AS ETAPA,
		M.CRIADO_EM AS [DATA]
	FROM
		INSCRICAO I
		INNER JOIN CANDIDATO C ON C.ID_CANDIDATO = I.ID_CANDIDATO
		INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
		INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
	WHERE
		I.ID_PROCESSO IN (13,14)
	UNION ALL
	/* PRÉ-MATRÍCULA */
	SELECT DISTINCT
		P.CODPERLET,
		UPPER(C.NOME) AS CANDIDATO,
		I.CODCURSO_PRETENDIDA AS CODCURSO,
		I.CODHABILITACAO_PRETENDIDA AS CODHABILITACAO,
		CASE
			WHEN UPPER(M.PERIODO_PRIMEIRA_OPCAO) = 'MANHA' THEN 'MANHÃ'
			WHEN UPPER(M.PERIODO_PRIMEIRA_OPCAO) = 'UNDEFINED' THEN 'MANHÃ'
			ELSE UPPER(M.PERIODO_PRIMEIRA_OPCAO)
			END AS TURNO,
		'4 - PRÉ-MATRÍCULA' AS ETAPA,
		PM.CRIADO_EM AS [DATA]
	FROM
		INSCRICAO I
		INNER JOIN CANDIDATO C ON C.ID_CANDIDATO = I.ID_CANDIDATO
		INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
		INNER JOIN PRE_MATRICULA PM ON PM.ID_INSCRICAO = I.ID_INSCRICAO
		INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
	WHERE
		I.ID_PROCESSO IN (13,14)
	UNION ALL
	/* RESERVA PAGA */
	SELECT
		P.CODPERLET,
		UPPER(C.NOME) AS CANDIDATO,
		I.CODCURSO_PRETENDIDA AS CODCURSO,
		I.CODHABILITACAO_PRETENDIDA AS CODHABILITACAO,
		CASE
			WHEN UPPER(M.PERIODO_PRIMEIRA_OPCAO) = 'MANHA' THEN 'MANHÃ'
			WHEN UPPER(M.PERIODO_PRIMEIRA_OPCAO) = 'UNDEFINED' THEN 'MANHÃ'
			ELSE UPPER(M.PERIODO_PRIMEIRA_OPCAO)
			END AS TURNO,
		'5 - MATRICULADO' AS ETAPA,
		BOL.MODIFICADO_EM AS [DATA]
	FROM
		INSCRICAO I
		INNER JOIN CANDIDATO C ON C.ID_CANDIDATO = I.ID_CANDIDATO
		INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
		INNER JOIN [STATUS] ST ON ST.ID_STATUS = I.ID_STATUS
		INNER JOIN PRE_MATRICULA PM ON PM.ID_INSCRICAO = I.ID_INSCRICAO
		INNER JOIN PRE_MATRICULA_CONTRATO_BOLETO PMCB ON PMCB.ID_PRE_MATRICULA = PM.ID_PRE_MATRICULA
		INNER JOIN BOLETO BOL ON BOL.ID_BOLETO = PMCB.ID_BOLETO
		INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
	WHERE
		I.ID_PROCESSO IN (13,14)
		AND I.ID_STATUS = 10
	)

SELECT
	FF.*,
	(SELECT SUBSTRING(MAX(ETAPA),5,LEN(MAX(ETAPA))-4) FROM FUNIL F WHERE F.CANDIDATO = FF.CANDIDATO) AS ETAPA_ATUAL,
	RCC.RM_SERIE AS SERIE
FROM
	FUNIL FF
	LEFT JOIN VW_RUBEUS_CODGRADE_CURSOS_NOMES RCC
				ON RCC.CODCURSO = FF.CODCURSO
				AND RCC.CODHABILITACAO = FF.CODHABILITACAO
				AND RCC.TURNO = CASE
									WHEN FF.TURNO IS NULL THEN 'GENÉRICO'
									WHEN FF.CODCURSO = '03' THEN 'MANHÃ'
									ELSE FF.TURNO END
ORDER BY
	FF.CANDIDATO,
	FF.ETAPA;