/*

	MÉDIA PARCIA E NECESSÁRIA - FUND 1 INTEGRAL - 1º SEM
	
	OBS_1:

	560	= 1º Semestre - Fundamental 1 - Período Integral
	562	= 1º Semestre - Fundamental 2 - Período Integral
	612    1º Semestre - Fundamental 1 - Período Integral (2024)
	613    2º Semestre - Fundamental 1 - Período Integral (2024)
	614    1º Semestre - Fundamental 2 - Período Integral (2024)
	615    2º Semestre - Fundamental 2 - Período Integral (2024)

*/

SELECT
	TB.ETAPA_PAI,
	TB.DESC_ETAPA_PAI,
	TB.SEMESTRE,
	TB.RA,
	TB.ALUNO,
	TB.CODTURMA,
	TB.IDTURMADISC,
	TB.CODDISC,
	TB.DISCIPLINA,
	TB.PESO_PARCIAL,
	TB.MEDIA_PARCIAL,
	        CASE
            WHEN TB.PESO_PARCIAL >= 100 THEN NULL
            ELSE CAST(CAST((600-(TB.MEDIA_PARCIAL * TB.PESO_PARCIAL))/(100-TB.PESO_PARCIAL) AS DECIMAL(10,1)) AS DECIMAL(10,2))
            END AS MEDIA_NECESSARIA,
	GETDATE() as 'ULTIMA_ATUALIZACAO',
	TB.CODTURMA2,
	TB.TIPO_DISCIPLINA,
	TB.PERIODO,
	TB.CODPERLET as 'ANO_LETIVO'
FROM (
	SELECT
		TB.RA,
		TB.ALUNO,
		TB.ETAPA_PAI,
		TB.DESC_ETAPA_PAI,
		TB.SEMESTRE,
		TB.IDTURMADISC,
		TB.CODDISC,
		TB.DISCIPLINA,
		TB.CODTURMA,
		CAST(CAST(SUM(((TB.NOTA_ALUNO/TB.NOTAMAXIMA)*10)*TB.PESO)/(SUM(TB.PESO)) AS DECIMAL(10,1)) AS DECIMAL(10,2)) AS MEDIA_PARCIAL,
		SUM(TB.PESO) AS PESO_PARCIAL,
		TB.CODTURMA2,
		TB.TIPO_DISCIPLINA,
		TB.PERIODO,
		TB.CODPERLET
	FROM (
		SELECT
			AVA.RA,
			PP.NOME AS ALUNO,
			MPL.CODTURMA,
			ATD.IDTURMADISC,
			STD.CODDISC,
			SD.NOME AS DISCIPLINA,
			ETP.ETAPA AS ETAPA_PAI,
			ETP.LABEL as SEMESTRE,
			ETP.DESCRICAO AS DESC_ETAPA_PAI,
			AV.NOME AS AVALIACAO,
			AV.TIPO AS TIPO_AVALIACAO,
			AV.PESO,
			AV.NOTAMAXIMA ,
			ATD.DATA AS DATA_APL_PROVA,
			AVA.NOTA AS NOTA_ALUNO,
			STD.CODTURMA as CODTURMA2,
			CASE	
				WHEN STD.CODDISC LIKE '%.I' THEN 'Interdisciplinar'
				WHEN STD.CODDISC LIKE '%.E' THEN 'Eletiva'
				WHEN (STD.CODDISC = 'ING' OR STD.CODDISC = 'ESP') THEN 'Turma Mista'
				ELSE 'Regular'
			END AS TIPO_DISCIPLINA,
			CASE WHEN STO.NOME = 'INTEGRAL' THEN 'INTEGRAL' ELSE 'PARCIAL' END AS PERIODO,
			SPL.CODPERLET
		FROM
			DiarioMB.dbo.ETAPAS ET
			INNER JOIN DiarioMB.dbo.ETAPAS ETP ON ETP.ETAPA = ET.ETAPAPAI
			INNER JOIN DiarioMB.dbo.AVALIACOES AV ON AV.ETAPA = ET.ETAPA
			INNER JOIN DiarioMB.dbo.AVALIACOESTURMASDISC ATD ON ATD.AVALIACAO = AV.AVALIACAO
			INNER JOIN DiarioMB.dbo.AVALIACOESALUNOS AVA ON AVA.AVALIACAO = AV.AVALIACAO
			INNER JOIN CorporeRM.dbo.SMATRICULA MAT ON MAT.CODCOLIGADA = ATD.CODCOLIGADA AND MAT.IDTURMADISC = ATD.IDTURMADISC AND MAT.RA = AVA.RA
			INNER JOIN CorporeRM.dbo.SMATRICPL MPL ON MPL.CODCOLIGADA = MAT.CODCOLIGADA AND MPL.IDPERLET = MAT.IDPERLET AND MPL.IDHABILITACAOFILIAL = MAT.IDHABILITACAOFILIAL AND MPL.RA = MAT.RA
			INNER JOIN CorporeRM.dbo.SALUNO SA ON SA.CODCOLIGADA = MPL.CODCOLIGADA AND SA.RA = MPL.RA
			INNER JOIN CorporeRM.dbo.PPESSOA PP ON PP.CODIGO = SA.CODPESSOA
			INNER JOIN CorporeRM.dbo.SPLETIVO SPL ON SPL.CODCOLIGADA = MPL.CODCOLIGADA AND SPL.IDPERLET = MPL.IDPERLET
			INNER JOIN CorporeRM.dbo.SSTATUS SST ON SST.CODCOLIGADA = MPL.CODCOLIGADA AND SST.CODSTATUS = MPL.CODSTATUS
			INNER JOIN CorporeRM.dbo.STURMADISC STD ON STD.CODCOLIGADA = MAT.CODCOLIGADA AND STD.IDTURMADISC = MAT.IDTURMADISC
			INNER JOIN CorporeRM.dbo.SDISCIPLINA SD ON SD.CODCOLIGADA = STD.CODCOLIGADA AND SD.CODDISC = STD.CODDISC
			INNER JOIN CorporeRM.dbo.STURNO STO ON STO.CODCOLIGADA = STD.CODCOLIGADA AND STO.CODTURNO = STD.CODTURNO
		WHERE
			AV.PUBLICAR = 1
			AND SPL.CODPERLET >= 2023
			AND ETP.ETAPA IN (560, 562, 561, 563, 612, 613, 614, 615) /* OBS_1 */
			AND SST.PLATIVO = 'S'
		) TB
	GROUP BY
		TB.RA,
		TB.ALUNO,
		TB.ETAPA_PAI,
		TB.DESC_ETAPA_PAI,
		TB.SEMESTRE,
		TB.IDTURMADISC,
		TB.CODDISC,
		TB.DISCIPLINA,
		TB.CODTURMA,
		TB.CODTURMA2,
		TB.TIPO_DISCIPLINA,
		TB.PERIODO,
		TB.CODPERLET
	) TB
ORDER BY
	TB.CODTURMA,
	TB.CODTURMA2,
	TB.RA,
	TB.CODDISC;