SELECT
    RCC.NOME_OFERTAS_CURSOS AS CURSO_INSC,
    RCC.UNIDADE_NOME AS UNIDADE_INSC,
    i.CODCURSO_PRETENDIDA,
    i.CODHABILITACAO_PRETENDIDA,
    LOWER(OI.NOME) AS ORIGEM_NOME,
    OI.CODIGO AS ORIGEM_COD,
    I.CRIADO_EM AS DT_CRIACAO_INSC,
	year(I.CRIADO_EM) as ano
FROM
    INSCRICAO I
    INNER JOIN CANDIDATO C ON C.ID_CANDIDATO = I.ID_CANDIDATO
    INNER JOIN ORIGEM_INSCRICAO OI ON OI.ID_ORIGEM_INSCRICAO = I.ID_ORIGEM_INSCRICAO
    INNER JOIN VW_RUBEUS_CODGRADE_CURSOS_NOMES RCC ON RCC.CODCURSO = I.CODCURSO_PRETENDIDA AND RCC.CODHABILITACAO = I.CODHABILITACAO_PRETENDIDA AND CASE WHEN RCC.CODCURSO = '03' THEN 'MANHÃ' ELSE 'GENÉRICO' END = RCC.TURNO
WHERE
    I.ID_PROCESSO = 13
    AND I.CRIADO_EM >= '2023-07-07';