    SELECT
        TB.ANOLETIVO,
        TB.NUCLEO,
        TB.CICLO,
        TB.SERIE,
        SUM(CASE WHEN TB.INSCRICOES IS NOT NULL THEN TB.INSCRICOES END) AS INSCRICOES,
        SUM(CASE WHEN TB.MANIFESTACOES IS NOT NULL THEN TB.MANIFESTACOES END) AS MANIFESTACOES,
        SUM(CASE WHEN TB.MATRICULAS IS NOT NULL THEN TB.MATRICULAS END) AS MATRICULADOS,
        SUM(CASE WHEN TB.CHAMADOS IS NOT NULL THEN TB.CHAMADOS END) AS CHAMADOS,
        SUM(CASE WHEN TB.DESISTENTES IS NOT NULL THEN TB.DESISTENTES END) AS DESISTENTES 
    FROM (
        /* INSCRIÇÃO */
        SELECT
            P.CODPERLET AS ANOLETIVO,
            CASE
                WHEN I.TURNO_PRETENDIDO = 'Integral' THEN 'INTEGRAL' ELSE 'PARCIAL'
                END AS NUCLEO,
            CASE
                WHEN I.CODCURSO_PRETENDIDA = '00' THEN 'INFANTIL'
                WHEN I.CODCURSO_PRETENDIDA = '01' THEN 'FUNDAMENTAL 1'
                WHEN I.CODCURSO_PRETENDIDA = '02' THEN 'FUNDAMENTAL 2'
                WHEN I.CODCURSO_PRETENDIDA = '03' THEN 'MÉDIO'
                END AS CICLO,
            G.NOME AS SERIE,
            COUNT(*) AS INSCRICOES,
            NULL AS MANIFESTACOES,
            NULL AS MATRICULAS,
            NULL AS CHAMADOS,
            NULL AS DESISTENTES
        FROM
            INSCRICAO I
            INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
            INNER JOIN GRADE G ON G.CODGRADE = CASE WHEN I.TURNO_PRETENDIDO = 'Integral' THEN CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA,'.1') ELSE CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA) END AND G.TURNO = CASE	WHEN I.TURNO_PRETENDIDO = 'Integral' THEN 'INTEGRAL' ELSE 'PARCIAL'	END
        WHERE
            P.ID_PROCESSO IN (13,14)
        GROUP BY
            I.TURNO_PRETENDIDO,
            P.CODPERLET,
            CODCURSO_PRETENDIDA,
            G.NOME
        UNION ALL
        /* MANIFESTAÇÃO */
        SELECT
            TB.CODPERLET AS ANOLETIVO,
            CASE WHEN TB.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN 'INTEGRAL' ELSE 'PARCIAL' END AS NUCLEO,
            CASE
                WHEN TB.CODCURSO_PRETENDIDA = '00' THEN 'INFANTIL'
                WHEN TB.CODCURSO_PRETENDIDA = '01' THEN 'FUNDAMENTAL 1'
                WHEN TB.CODCURSO_PRETENDIDA = '02' THEN 'FUNDAMENTAL 2'
                WHEN TB.CODCURSO_PRETENDIDA = '03' THEN 'MÉDIO'
                END AS CICLO,
            G.NOME AS SERIE,
            NULL AS INSCRICOES,
            COUNT(*) AS MANIFESTACOES,
            NULL AS MATRICULAS,
            NULL AS CHAMADOS,
            NULL AS DESISTENTES
        FROM
            (
            SELECT
                P.CODPERLET,
                I.CODCURSO_PRETENDIDA,
                I.CODHABILITACAO_PRETENDIDA,
                M.PERIODO_PRIMEIRA_OPCAO,
                CASE
                    WHEN M.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA,'.1')
                    ELSE CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA)
                    END AS CODGRADE
            FROM
                INSCRICAO I
                INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
                INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
            WHERE
                P.ID_PROCESSO IN (13,14)
            ) TB
            INNER JOIN GRADE G ON G.CODGRADE = TB.CODGRADE AND G.TURNO = CASE WHEN TB.PERIODO_PRIMEIRA_OPCAO = 'Integral' THEN 'INTEGRAL' ELSE 'PARCIAL'	END
        GROUP BY
            TB.CODPERLET,
            TB.PERIODO_PRIMEIRA_OPCAO,
            TB.CODCURSO_PRETENDIDA,
            G.NOME
        UNION ALL
        /* PRE-MATRICULA */
        SELECT
            TB.CODPERLET AS ANOLETIVO,
            CASE WHEN TB.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN 'INTEGRAL' ELSE 'PARCIAL' END AS NUCLEO,
            CASE
                WHEN TB.CODCURSO_PRETENDIDA = '00' THEN 'INFANTIL'
                WHEN TB.CODCURSO_PRETENDIDA = '01' THEN 'FUNDAMENTAL 1'
                WHEN TB.CODCURSO_PRETENDIDA = '02' THEN 'FUNDAMENTAL 2'
                WHEN TB.CODCURSO_PRETENDIDA = '03' THEN 'MÉDIO'
                END AS CICLO,
            G.NOME AS SERIE,
            NULL AS INSCRICOES,
            NULL AS MANIFESTACOES,
            COUNT(*) AS MATRICULAS,
            NULL AS CHAMADOS,
            NULL AS DESISTENTES
        FROM
            (
            SELECT
                P.CODPERLET,
                I.CODCURSO_PRETENDIDA,
                I.CODHABILITACAO_PRETENDIDA,
                M.PERIODO_PRIMEIRA_OPCAO,
                CASE
                    WHEN M.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA,'.1')
                    ELSE CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA)
                    END AS CODGRADE,
                I.ID_STATUS
            FROM
                INSCRICAO I
                INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
                INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
                INNER JOIN PRE_MATRICULA PM ON PM.ID_INSCRICAO = I.ID_INSCRICAO
            WHERE
                P.ID_PROCESSO IN (13,14)
                AND I.ID_STATUS = 10 /* NA ETAPA RESERVA PAGA NO RUBEUS */
            ) TB
            INNER JOIN GRADE G ON G.CODGRADE = TB.CODGRADE AND G.TURNO = CASE WHEN TB.PERIODO_PRIMEIRA_OPCAO = 'Integral' THEN 'INTEGRAL' ELSE 'PARCIAL'	END
        GROUP BY
            TB.CODPERLET,
            TB.PERIODO_PRIMEIRA_OPCAO,
            TB.CODCURSO_PRETENDIDA,
            G.NOME
        UNION ALL
        /* CHAMADOS */
        SELECT
            TB.CODPERLET AS ANOLETIVO,
            CASE WHEN TB.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN 'INTEGRAL' ELSE 'PARCIAL' END AS NUCLEO,
            CASE
                WHEN TB.CODCURSO_PRETENDIDA = '00' THEN 'INFANTIL'
                WHEN TB.CODCURSO_PRETENDIDA = '01' THEN 'FUNDAMENTAL 1'
                WHEN TB.CODCURSO_PRETENDIDA = '02' THEN 'FUNDAMENTAL 2'
                WHEN TB.CODCURSO_PRETENDIDA = '03' THEN 'MÉDIO'
                END AS CICLO,
            G.NOME AS SERIE,
            NULL AS INSCRICOES,
            NULL AS MANIFESTACOES,
            NULL AS MATRICULADOS,
            COUNT(*) AS CHAMADOS,
            NULL AS DESISTENTES
        FROM
            (
            SELECT
                P.CODPERLET,
                I.CODCURSO_PRETENDIDA,
                I.CODHABILITACAO_PRETENDIDA,
                M.PERIODO_PRIMEIRA_OPCAO,
                CASE
                    WHEN M.PERIODO_PRIMEIRA_OPCAO = 'INTEGRAL' THEN CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA,'.1')
                    ELSE CONCAT(I.CODCURSO_PRETENDIDA,I.CODHABILITACAO_PRETENDIDA)
                    END AS CODGRADE,
                I.ID_STATUS
            FROM
                INSCRICAO I
                INNER JOIN PROCESSO P ON P.ID_PROCESSO = I.ID_PROCESSO
                INNER JOIN MANIFESTACAO M ON M.ID_INSCRICAO = I.ID_INSCRICAO
                INNER JOIN PRE_MATRICULA PM ON PM.ID_INSCRICAO = I.ID_INSCRICAO
            WHERE
                P.ID_PROCESSO IN (13,14) 
            ) TB
            INNER JOIN GRADE G ON G.CODGRADE = TB.CODGRADE AND G.TURNO = CASE WHEN TB.PERIODO_PRIMEIRA_OPCAO = 'Integral' THEN 'INTEGRAL' ELSE 'PARCIAL'	END
        GROUP BY
            TB.CODPERLET,
            TB.PERIODO_PRIMEIRA_OPCAO,
            TB.CODCURSO_PRETENDIDA,
            G.NOME
        UNION ALL
        /* DESISTENTES */
        SELECT
            TB.ANOLETIVO,
            TB.NUCLEO,
            TB.CICLO,
            TB.SERIE,
            NULL AS INSCRICOES,
            NULL AS MANIFESTACOES,
            NULL AS MATRICULADOS,
            NULL AS CHAMADOS,
            COUNT(*) AS DESISTENTES
        FROM
            (
            SELECT
                '2024' AS ANOLETIVO,
                CASE
                    WHEN RCC.TURNO = 'Integral' THEN 'INTEGRAL'
                    WHEN RCC.TURNO IN ('Manhã','Tarde') THEN 'PARCIAL'
                    END AS NUCLEO,
                CASE
                    WHEN RCC.CODCURSO IN ('00', '00.1') THEN 'INFANTIL'
                    WHEN RCC.CODCURSO IN ('01', '01.1') THEN 'FUNDAMENTAL 1'
                    WHEN RCC.CODCURSO IN ('02', '02.1') THEN 'FUNDAMENTAL 2'
                    WHEN RCC.CODCURSO = '03' THEN 'MÉDIO'
                    END AS CICLO,
                RCC.RM_SERIE AS SERIE
            FROM
                IngressoMB.dbo.RUBEUS_REGISTROS_2024 RR
                INNER JOIN IngressoMB.dbo.VW_RUBEUS_CODGRADE_CURSOS_NOMES RCC ON RCC.RUBEUS_OFERTA = RR.[Código do curso]
            WHERE
                [Status] = 'Perdida'
                AND Etapa IN ('Chamados','Pré Matrícula','Reserva','Reserva paga')
            ) TB
        GROUP BY
            TB.ANOLETIVO,
            TB.NUCLEO,
            TB.CICLO,
            TB.SERIE
        ) TB
    GROUP BY
        TB.ANOLETIVO,
        TB.NUCLEO,
        TB.CICLO,
        TB.SERIE;