	SELECT DISTINCT
        SPL.CODPERLET,
        ISNULL(SHF.CODGRADE,STH.CODGRADE) AS CODGRADE,
        CASE
			WHEN SHF.CODGRADE = '0101' OR STH.CODGRADE = '0101' THEN '1º Ano'
			WHEN SHF.CODGRADE = '0102' OR STH.CODGRADE = '0102' THEN '2º Ano'
			WHEN SHF.CODGRADE = '0103' OR STH.CODGRADE = '0103' THEN '3º Ano'
			WHEN SHF.CODGRADE = '0104' OR STH.CODGRADE = '0104' THEN '4º Ano'
			WHEN SHF.CODGRADE = '0105' OR STH.CODGRADE = '0105' THEN '5º Ano'
			WHEN SHF.CODGRADE = '0206' OR STH.CODGRADE = '0206' THEN '6º Ano'
			WHEN SHF.CODGRADE = '0207' OR STH.CODGRADE = '0207' THEN '7º Ano'
			WHEN SHF.CODGRADE = '0208' OR STH.CODGRADE = '0208' THEN '8º Ano'
			WHEN SHF.CODGRADE = '0209' OR STH.CODGRADE = '0209' THEN '9º Ano'
            END AS SERIE,
            STD.CODTURMA,
        ET.DESCRICAO AS DESC_ETAPA,
        ETP.LABEL,
        STD.CODDISC,
        SD.NOME AS DISCIPLINA,
		CASE	
			WHEN STD.CODDISC LIKE '%.I' THEN 'Interdisciplinar'
			WHEN STD.CODDISC LIKE '%.E' THEN 'Eletiva'
			WHEN (STD.CODDISC = 'ING' OR STD.CODDISC = 'ESP') THEN 'Turma Mista'
			ELSE 'Regular'
			END AS TIPO_DISCIPLINA,
        AV.AVALIACAO ID_AVALIACAO,
        AV.NOME AS AVALIACAO,
        AV.PUBLICAR,
        AV.PESO,
        TA.DESCRICAO AS TIPO_AVALIACAO,
        TE.NOME AS ETAPA,
        ATD.DATA AS DATA_PROVA,
        --AV.DATAHORAREC AS DATA_CRIACAO_AVALIACAO,
		    CASE 
        WHEN av.ULTIMOPERIODO = 1 THEN 'Sim'
        ELSE 'Não'
    END AS ULTIMOPERIODO_STATUS,
        GETDATE() AS 'DATA_ULT_ATUALIZACAO_DADOS'
    FROM
        AVALIACOES AV
        INNER JOIN AVALIACOESTURMASDISC ATD ON ATD.AVALIACAO = AV.AVALIACAO
        INNER JOIN ETAPAS ET ON ET.ETAPA = AV.ETAPA
        INNER JOIN ETAPAS ETP ON ETP.ETAPA = ET.ETAPAPAI
        INNER JOIN TIPOSETAPAS TE ON TE.TIPOETAPA = ETP.TIPOETAPA
        INNER JOIN TIPOSAVALIACOES TA ON TA.TIPO = AV.TIPO
        INNER JOIN CorporeRM.dbo.STURMADISC STD ON STD.CODCOLIGADA = ATD.CODCOLIGADA AND STD.IDTURMADISC = ATD.IDTURMADISC
        LEFT JOIN CorporeRM.dbo.SHABILITACAOFILIAL SHF ON SHF.CODCOLIGADA = STD.CODCOLIGADA AND SHF.IDHABILITACAOFILIAL = STD.IDHABILITACAOFILIAL
        INNER JOIN CorporeRM.dbo.SDISCIPLINA SD ON SD.CODCOLIGADA = STD.CODCOLIGADA AND SD.CODDISC = STD.CODDISC
        INNER JOIN CorporeRM.dbo.SPLETIVO SPL ON SPL.CODCOLIGADA = STD.CODCOLIGADA AND SPL.IDPERLET = STD.IDPERLET
        INNER JOIN CorporeRM.dbo.STURMADISCHABILITACAOPL STH ON STH.CODCOLIGADA = STD.CODCOLIGADA AND STH.CODFILIAL = STD.CODFILIAL AND STH.IDTURMADISC = STD.IDTURMADISC
    WHERE
        STD.CODCOLIGADA = 1
		AND STD.CODFILIAL in (1,2)		/* PARCIAL */
        AND SPL.CODPERLET >= 2023  /* ANO LETIVO */
        AND ETP.TIPOETAPA = 1       /* REGULAR */
        AND STD.CODDISC NOT LIKE '%.C'
        AND AV.EXIBEBI = 1
		and ET.DESCRICAO like '%Parcial'
    ORDER BY
        CODGRADE,
        LABEL,
        DISCIPLINA,
        ATD.DATA;